name: Windows / Linux KVM support high spec (12gb ram / 60gb ssd / 3core / VT-x support)

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
      link_iso:
        description: 'https://software.download.prss.microsoft.com/dbazure/Win10_22H2_English_x64v1.iso?t=b94e0d00-caaf-4909-a8c3-70cd13e36da0&e=1704091437&h=78e1da47e9c76e2c1fac1e035c9ce922b7456015325d930d09a701366a6b52c8'
        required: true
 
jobs:
  build:
    runs-on: windows
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm -y
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
          tar -xf ngrok-v3-stable-windows-amd64.zip
          chmod +x ngrok
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          nohup ./ngrok tcp --region ap 5900 &>/dev/null &
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo qemu-img create -f qcow2 /mnt/a.qcow2 60G
          wget -O file.iso "${{ github.event.inputs.link_iso }}"
          wget -O driver.iso https://computernewb.com/isos/driver/virtio-win-0.1.240.iso
          echo "bình thường sẽ được 20 - 30 phút nhé còn ae nào may mắn đc 2-4h"
          sudo qemu-system-x86_64 -M q35,usb=on -device usb-tablet -cpu host -smp 3 -m 12G -device virtio-balloon-pci -vga qxl -net nic,netdev=n0 -netdev user,id=n0 -boot c -device virtio-serial-pci -device virtio-rng-pci -enable-kvm -drive file=/mnt/a.qcow2 -drive file=file.iso,media=cdrom -drive file=driver.iso,media=cdrom  -vnc :0 -bios /usr/share/ovmf/OVMF.fd
          
